### ISSUE TITLE
Fairness control can't handle many cohorts at once

### ISSUE THREAD

**Issue by diehlbw** [epic-open-source/seismometer#66]
## Problem Summary
Temporary file caching can cause errors due to loo long filenames if there are a large number of cohorts.
This probably has other issues as well: like long compute time, decreased usability due to wide/scrolling display

## Impact
Can't use ExploreFairnessAudit with "large" number of cohorts.

## Possible Solution
Add an additional selector on cohorts and enforce a max type -- this could hide fairness issues
Or change it into vertically stacked outputs, each having a maximum number of cohort attributes

**Comment by diehlbw** [comment]
@gbowlin thoughts on this issue/solution?

**Comment by gbowlin** [comment]
I like the idea of selecting a subset of the cohort columns.  This would also help with grouping them into common themes, like model features (should not be fair) and non-model features (demographics that should be fair). 

Also setting a maximum to compute at once would be nice since each split does take a while to compute.

**Comment by diehlbw** [comment]
cohort_comparison_report also can hit this issue, since it generates names in the same way.  
That said it's not as hard a stop since you have to manually select all the cohorts vs the Explore control defaulting the values (so cant bypass it)
